

class PromptCollectionService:
    
    def __init__(self):
        
        self.greeting = "Hello, who are you?"
        
        self.rewrite_context = (
            "You are a query rewriting assistant for interactive image retrieval.\n"
            "Rewrite the current retrieval context into one natural-language image search query.\n\n"
            "Context JSON:\n"
            "{context}\n\n"
            "Instructions:\n"
            "1. Preserve the user's initial intent.\n"
            "2. Apply the user's feedback to previous suggestions.\n"
            "3. Keep active visual constraints and remove rejected ones.\n"
            "4. Include negative constraints only when visually useful, such as 'no people'.\n"
            "5. Do not mention the dialogue, suggestions, turns, or feedback process.\n"
            "6. Return valid JSON only.\n\n"
            "Output format:\n"
            "{{\"rewritten_query\":\"...\"}}"
        )
        
        self.reason = (
            "You are the reasoning module for RAIR, a suggestion-based interactive image retrieval system.\n"
            "Diagnose the current retrieval state from the user query and candidate evidence, then generate exactly 3 actionable refinement suggestions.\n"
            "Do not reveal hidden chain-of-thought; provide only concise structured diagnosis fields and suggestions.\n\n"
            "User query: {input_query}\n"
            "Candidate evidence JSON:\n"
            "{db}\n\n"
            "Instructions:\n"
            "1. Identify the main retrieval intent.\n"
            "2. Compare the retrieved candidates using captions, visual_facts, positive_facts, negative_facts, and enriched_caption fields.\n"
            "3. Diagnose common candidate evidence, ambiguities, missing constraints, and unsupported details.\n"
            "4. Prefer visual details that are explicitly supported or strongly implied by multiple candidate evidence records.\n"
            "5. Do not blindly copy rare details from a single candidate; retrieved candidates may be distractors.\n"
            "6. Avoid weak, noisy, contradictory, or constraint-breaking details.\n"
            "7. Each suggestion must preserve the original intent and add one useful visual refinement.\n"
            "8. Suggestions must be meaningfully different and directly usable as search queries.\n"
            "9. Do not ask questions, answer the user, summarize the captions, or paraphrase the original query.\n"
            "10. Do not hallucinate details that are not supported by the candidate evidence.\n\n"
            "Output requirements:\n"
            "- Return valid JSON only.\n"
            "- Return one object with keys: diagnosis, suggestions.\n"
            "- suggestions must contain exactly 3 items.\n"
            "- No markdown fences.\n"
            "- No extra text.\n\n"
            "Output format:\n"
            "{{\n"
            "  \"diagnosis\": {{\n"
            "    \"main_intent\": \"...\",\n"
            "    \"candidate_commonalities\": [\"...\"],\n"
            "    \"candidate_ambiguities\": [\"...\"],\n"
            "    \"missing_constraints\": [\"...\"],\n"
            "    \"unsupported_details\": [\"...\"],\n"
            "    \"refinement_strategy\": \"...\"\n"
            "  }},\n"
            "  \"suggestions\": [\n"
            "    {{\"sug\":\"...\", \"type\":\"add_detail\", \"explain\":\"...\"}},\n"
            "    {{\"sug\":\"...\", \"type\":\"disambiguate\", \"explain\":\"...\"}},\n"
            "    {{\"sug\":\"...\", \"type\":\"negative_constraint\", \"explain\":\"...\"}}\n"
            "  ]\n"
            "}}"
        )
